image: erlang:19.1

before_script:
  - apt-get update -y
  - apt-get -y install g++-4.9
  - export CXX=g++-4.9

test:
  script:
    - make apply
    - make rel
    - ./_build/prod/rel/barrel/bin/barrel_http start
    - sleep 5
    - ./_build/prod/rel/barrel/bin/barrel_http ping
    - 'curl -X PUT --header "Content-Type: application/json" --header "Accept: application/json" "http://localhost:8080/testdb/db1"'
    - 'curl -X GET --header "Accept: application/json" "http://localhost:8080/testdb/db1/_all_docs"'
    - ./_build/prod/rel/barrel/bin/barrel_http stop
