image: erlang:19.2.2

before_script:
  - apt-get update -y
  - apt-get -y install g++-4.9
  - export CXX=g++-4.9

variables:
  ERL_AFLAGS: "-smp enable"

after_failure:
  - cat `ls -1 -d -t _build/test/logs/ct_run* | head -1`/log/error.log
  - cat `ls -1 -d -t _build/test/logs/ct_run* | head -1`/log/crash.log
  - tail -100 `ls -1 -d -t _build/test/logs/ct_run* | head -1`/log/console.log

test:
  artifacts:
    when: always
    paths:
    - _build/test/logs

  script:
    - ./support/rebar3 eunit
    - ./support/rebar3 ct
