image: erlang:19.1

before_script:
  - apt-get update -y
  - apt-get -y install g++-4.9
  - export CXX=g++-4.9

test:
  script:
    - make apply
    - make rel
    - ./_build/default/rel/barrel/bin/barrel_http start
    - sleep 5
    - ./_build/default/rel/barrel/bin/barrel_http ping
    - 'curl -f -X GET --header "Accept: application/json" "http://localhost:8080/testdb"'
    - ./_build/default/rel/barrel/bin/barrel_http stop
