language: erlang

otp_release:
    - 18.0
    - 18.1

install:
    - "./support/bootstrap_travis.sh"

script: "./rebar3 compile"

notifications:
    irc:
        - "irc.freenode.org#barreldb"
    email:
        - "bchesneay@gmail.com"
