language: erlang

otp_release:
  - 19.2

before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install g++-4.9

before_script:
    - kerl list installations
    - curl -L https://s3.amazonaws.com/rebar3/rebar3
    - chmod +x rebar3
    - export CXX=g++-4.9

script:
    - ./rebar3 eunit
    - ./rebar3 ct