sudo: false
dist: trusty
language: erlang

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
      packages: ['g++-6', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libgflags-dev']

otp_release:
  - 19.2

env:
  - JOB_NAME=clang

before_script:
  - kerl list installations
  - curl -L https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - CXX=g++-6; fi


script:
  - - ${CXX} --version
  - ./rebar3 eunit
  - ./rebar3 ct

notifications:
  email:
    - team@barrel-db.org