sudo: false
dist: trusty
language: erlang

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
      packages: ['g++-6', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libgflags-dev']

otp_release:
  - 19.2

before_script:
  - kerl list installations
  - CXX=g++-6

script:
  - ./support/rebar3 eunit
  - ./support/rebar3 ct

addons:
  artifacts: true
  paths:
    - _build/test/logs

notifications:
  email:
    - team@barrel-db.org