language: erlang

otp_release:
    - 18.0
    - 18.1

before_script:
    - "./support/bootstrap_travis.sh"


script: "make"

notifications:
    irc:
        - "irc.freenode.org#barreldb"
    recipients:
        - "bchesneay@gmail.com"
