image: erlang:19.1

before_script:
  - apt-get update -y
  - apt-get -y install g++-4.9
  - export CXX=g++-4.9

test:
  script:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod +x rebar3
    - ./rebar3 --version
    - ./rebar3 eunit
    - ./rebar3 ct

